"""Multilingual vocabulary linking user phrasing to business tables.

Used by the schema retriever (which tables are relevant?) and the heuristic
router (does this question need the database at all?). Terms cover English,
Bengali script and common Banglish spellings.
"""

from __future__ import annotations

TABLE_KEYWORDS: dict[str, list[str]] = {
    "orders": [
        "order",
        "orders",
        "sale",
        "sales",
        "revenue",
        "income",
        "turnover",
        "purchase",
        "purchased",
        "bought",
        "channel",
        "aov",
        "average order",
        "spent",
        "spend",
        "অর্ডার",
        "বিক্রি",
        "বিক্রয়",
        "আয়",
        "রেভিনিউ",
        "কেনা",
        "খরচ",
        "bikri",
        "bikroy",
        "kena",
        "kinse",
        "kinechhe",
        "khoroch",
        "cancelled",
        "canceled",
        "বাতিল",
        "order",
        "sell",
        "sales",
    ],
    "order_items": [
        "sold",
        "selling",
        "best-selling",
        "best selling",
        "top-selling",
        "units",
        "quantity",
        "most sold",
        "sell",
        "item",
        "items",
        "বিক্রি",
        "বেশি বিক্রি",
        "পরিমাণ",
        "beshi sell",
        "beshi bikri",
        "sell hoise",
        "sell hoyeche",
    ],
    "products": [
        "product",
        "products",
        "item",
        "sku",
        "brand",
        "price",
        "priced",
        "warranty",
        "catalog",
        "catalogue",
        "discontinued",
        "margin",
        "cost",
        "পণ্য",
        "প্রোডাক্ট",
        "দাম",
        "ব্র্যান্ড",
        "ওয়ারেন্টি",
        "ponno",
        "dam",
        "dam koto",
    ],
    "categories": ["category", "categories", "segment", "ক্যাটাগরি", "বিভাগ", "ধরন", "catagory"],
    "customers": [
        "customer",
        "customers",
        "client",
        "clients",
        "buyer",
        "buyers",
        "member",
        "members",
        "membership",
        "tier",
        "gold",
        "platinum",
        "silver",
        "bronze",
        "country",
        "city",
        "highest-value",
        "high-value",
        "loyal",
        "গ্রাহক",
        "কাস্টমার",
        "ক্রেতা",
        "সদস্য",
        "বাংলাদেশে",
        "দেশ",
        "শহর",
        "grahok",
        "kastomar",
        "customer",
    ],
    "payments": [
        "payment",
        "payments",
        "paid",
        "bkash",
        "nagad",
        "card",
        "cash on delivery",
        "cod",
        "transaction",
        "bank transfer",
        "failed payment",
        "পেমেন্ট",
        "বিকাশ",
        "নগদ",
        "লেনদেন",
        "payment method",
    ],
    "inventory": [
        "stock",
        "inventory",
        "warehouse",
        "reorder",
        "in stock",
        "out of stock",
        "available",
        "on hand",
        "restock",
        "মজুদ",
        "স্টক",
        "গুদাম",
        "stock koto",
        "stock ache",
    ],
    "returns": [
        "return",
        "returns",
        "returned",
        "refund",
        "refunds",
        "refunded",
        "defective",
        "damaged",
        "return rate",
        "ফেরত",
        "রিটার্ন",
        "রিফান্ড",
        "ferot",
        "return hoise",
    ],
    "reviews": [
        "review",
        "reviews",
        "rating",
        "ratings",
        "stars",
        "feedback",
        "rated",
        "রিভিউ",
        "রেটিং",
        "মতামত",
    ],
}

# Strong signals of aggregation over business data (counts, totals, rankings, periods).
# Entity words alone ("refund", "member") are NOT enough: policy questions mention them too.
ANALYTICS_TERMS: list[str] = [
    "how many",
    "total",
    "count",
    "number of",
    "average",
    "avg",
    "sum",
    "top",
    "highest",
    "lowest",
    "most",
    "least",
    "rank",
    "trend",
    "per month",
    "monthly",
    "last month",
    "this month",
    "last year",
    "this year",
    "last quarter",
    "last week",
    "last 30 days",
    "compare",
    "growth",
    "percentage of",
    "list",
    "show me",
    "who are",
    "মোট",
    "কতগুলো",
    "কতজন",
    "সবচেয়ে",
    "সর্বোচ্চ",
    "সর্বনিম্ন",
    "গড়",
    "গত",
    "তালিকা",
    "দেখাও",
    "kotogula",
    "koto gula",
    "koto jon",
    "kotojon",
    "shobcheye",
    "sobcheye",
    "beshi",
    "gorbo",
    "goto mash",
    "last mash",
    "last month e",
    "dekhao",
]

# Signals that a question is about company documents: policies, rules, entitlements.
DOCUMENT_TERMS: list[str] = [
    "policy",
    "policies",
    "handbook",
    "guideline",
    "guidelines",
    "rule",
    "rules",
    "procedure",
    "terms and conditions",
    "eligible",
    "eligibility",
    "entitled",
    "benefit",
    "benefits",
    "faq",
    "document",
    "according to",
    "allowed",
    "not allowed",
    "cannot",
    "can't",
    "leave",
    "warranty",
    "shipping",
    "delivery",
    "refund period",
    "return window",
    "how do i",
    "how to",
    "how long",
    "do i",
    "can i",
    "need to",
    "what does our",
    "what does the policy",
    "what is our",
    "what are our",
    "employee",
    "employees",
    "holiday",
    "working hours",
    "dress code",
    "cost",
    "fee",
    "charge",
    "minimum",
    "maximum",
    "limit",
    "requirement",
    "requirements",
    "bonus",
    "discount",
    "receive",
    "covered",
    "cover",
    "store credit",
    "নীতি",
    "নিয়ম",
    "পলিসি",
    "নির্দেশিকা",
    "ছুটি",
    "সুবিধা",
    "শর্ত",
    "প্রক্রিয়া",
    "হ্যান্ডবুক",
    "ডকুমেন্ট",
    "অনুযায়ী",
    "কর্মচারী",
    "ডেলিভারি",
    "চার্জ",
    "ছাড়",
    "শতাংশ",
    "সীমা",
    "কত দিন",
    "niti",
    "niyom",
    "policy ki",
    "chuti",
    "shubidha",
    "kivabe",
    "ki vabe",
    "lage",
    "pete",
    "pabo",
    "koto din",
    "korte hoy",
    "charge koto",
]

# Words that point at the user's own company rather than general knowledge.
COMPANY_TERMS: list[str] = [
    "our",
    "we",
    "us",
    "company",
    "nexa",
    "store",
    "shop",
    "আমাদের",
    "আমরা",
    "কোম্পানি",
    "কোম্পানির",
    "amader",
    "amra",
    "company",
]
