"""Initial schema: pgvector, app tables, commerce tables and the read-only SQL role.

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 18:45:31.465337
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from app.core.config import get_settings

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _quote_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _quote_ident(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def _create_readonly_role() -> None:
    """Least-privilege role used only by the Text-to-SQL executor."""
    settings = get_settings()
    role = _quote_ident(settings.sql_readonly_user)
    password = _quote_literal(settings.sql_readonly_password.get_secret_value())
    timeout = int(settings.sql_statement_timeout_ms)
    op.execute(
        f"""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = {_quote_literal(settings.sql_readonly_user)}) THEN
                CREATE ROLE {role} LOGIN PASSWORD {password}
                    NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION CONNECTION LIMIT 20;
            ELSE
                ALTER ROLE {role} WITH LOGIN PASSWORD {password}
                    NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION CONNECTION LIMIT 20;
            END IF;
        END
        $$;
        """
    )
    op.execute(f"ALTER ROLE {role} SET default_transaction_read_only = on")
    op.execute(f"ALTER ROLE {role} SET statement_timeout = {timeout}")
    op.execute(f"ALTER ROLE {role} SET idle_in_transaction_session_timeout = 10000")
    op.execute(f"ALTER ROLE {role} SET search_path = commerce")
    op.execute(f"ALTER ROLE {role} SET work_mem = '16MB'")
    op.execute(f"REVOKE ALL ON SCHEMA public FROM {role}")
    op.execute(f"GRANT USAGE ON SCHEMA commerce TO {role}")
    op.execute(f"GRANT SELECT ON ALL TABLES IN SCHEMA commerce TO {role}")
    op.execute(f"ALTER DEFAULT PRIVILEGES IN SCHEMA commerce GRANT SELECT ON TABLES TO {role}")


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE SCHEMA IF NOT EXISTS commerce")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Category display name.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Short category description.'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name')),
    schema='commerce',
    comment='Product categories (e.g. Electronics, Books).'
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False, comment='Customer full name.'),
    sa.Column('email', sa.String(length=320), nullable=False, comment='Customer email.'),
    sa.Column('phone', sa.String(length=30), nullable=True, comment='Contact phone number.'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment="'male' or 'female'."),
    sa.Column('city', sa.String(length=100), nullable=False, comment="City of residence, e.g. 'Dhaka'."),
    sa.Column('country', sa.String(length=100), nullable=False, comment="Country of residence, e.g. 'Bangladesh', 'India'."),
    sa.Column('membership_tier', sa.String(length=20), nullable=False, comment="Loyalty tier: 'Bronze', 'Silver', 'Gold' or 'Platinum' (benefits are defined in the Customer Membership Policy document)."),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Account sign-up time.'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('email', name=op.f('uq_customers_email')),
    schema='commerce',
    comment='Customers who have an account with the store.'
    )
    op.create_index('ix_customers_country', 'customers', ['country'], unique=False, schema='commerce')
    op.create_index('ix_customers_membership_tier', 'customers', ['membership_tier'], unique=False, schema='commerce')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=30), nullable=False, comment="Human-readable order number, e.g. 'NX-2026-000123'."),
    sa.Column('customer_id', sa.Integer(), nullable=False, comment='Customer who placed the order.'),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False, comment='When the order was placed.'),
    sa.Column('status', sa.String(length=20), nullable=False, comment="One of 'pending', 'processing', 'shipped', 'delivered', 'cancelled'."),
    sa.Column('channel', sa.String(length=20), nullable=False, comment="Sales channel: 'web', 'mobile_app' or 'store'."),
    sa.Column('shipping_city', sa.String(length=100), nullable=False, comment='Delivery city.'),
    sa.Column('shipping_country', sa.String(length=100), nullable=False, comment='Delivery country.'),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False, comment='Sum of line totals in BDT.'),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Order-level discount in BDT.'),
    sa.Column('shipping_fee', sa.Numeric(precision=12, scale=2), nullable=False, comment='Shipping fee in BDT.'),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Amount charged: subtotal - discount_amount + shipping_fee (BDT).'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment="Always 'BDT'."),
    sa.ForeignKeyConstraint(['customer_id'], ['commerce.customers.id'], name=op.f('fk_orders_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('order_number', name=op.f('uq_orders_order_number')),
    schema='commerce',
    comment="Customer orders. Revenue = SUM(total_amount) of orders whose status is not 'cancelled'."
    )
    op.create_index('ix_orders_customer_id', 'orders', ['customer_id'], unique=False, schema='commerce')
    op.create_index('ix_orders_order_date', 'orders', ['order_date'], unique=False, schema='commerce')
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False, schema='commerce')
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=40), nullable=False, comment='Stock keeping unit code.'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Product name.'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='Category of the product.'),
    sa.Column('brand', sa.String(length=100), nullable=False, comment='Brand / manufacturer.'),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Current list price in BDT.'),
    sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Unit purchase cost in BDT.'),
    sa.Column('warranty_months', sa.SmallInteger(), nullable=False, comment='Manufacturer warranty length in months (0 = none).'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='False if discontinued.'),
    sa.Column('launched_at', sa.Date(), nullable=False, comment='Date the product was first listed.'),
    sa.ForeignKeyConstraint(['category_id'], ['commerce.categories.id'], name=op.f('fk_products_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('sku', name=op.f('uq_products_sku')),
    schema='commerce',
    comment='Catalog of products sold by the company.'
    )
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False, schema='commerce')
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_documents_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_checksum'), 'documents', ['checksum'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('route', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('tools_used', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('total_ms', sa.Integer(), nullable=True),
    sa.Column('trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_agent_runs_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_runs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_conversation_id'), 'agent_runs', ['conversation_id'], unique=False)
    op.create_index('ix_agent_runs_user_created', 'agent_runs', ['user_id', 'created_at'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='Stocked product.'),
    sa.Column('warehouse', sa.String(length=60), nullable=False, comment="'Dhaka Central', 'Chattogram Hub' or 'Sylhet Depot'."),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False, comment='Units physically in stock.'),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False, comment='Units reserved for open orders.'),
    sa.Column('reorder_level', sa.Integer(), nullable=False, comment='Restock when quantity_on_hand falls below this level.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last stock update.'),
    sa.ForeignKeyConstraint(['product_id'], ['commerce.products.id'], name=op.f('fk_inventory_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory')),
    sa.UniqueConstraint('product_id', 'warehouse', name='uq_inventory_product_warehouse'),
    schema='commerce',
    comment='Current stock per product per warehouse. Total stock of a product = SUM(quantity_on_hand) across warehouses.'
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='Parent order.'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='Product purchased.'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Units purchased.'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Price per unit at purchase (BDT).'),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Line discount in BDT.'),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False, comment='quantity * unit_price - discount_amount (BDT).'),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_quantity_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['commerce.orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['commerce.products.id'], name=op.f('fk_order_items_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items')),
    schema='commerce',
    comment='Line items of each order. Units sold = SUM(quantity); product revenue = SUM(line_total).'
    )
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False, schema='commerce')
    op.create_index('ix_order_items_product_id', 'order_items', ['product_id'], unique=False, schema='commerce')
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='Order being paid.'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Payment amount in BDT.'),
    sa.Column('method', sa.String(length=30), nullable=False, comment="'bkash', 'nagad', 'card', 'cash_on_delivery' or 'bank_transfer'."),
    sa.Column('status', sa.String(length=20), nullable=False, comment="'completed', 'pending', 'failed' or 'refunded'."),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True, comment='When the payment settled (NULL if not settled).'),
    sa.Column('transaction_ref', sa.String(length=60), nullable=False, comment='Gateway reference.'),
    sa.ForeignKeyConstraint(['order_id'], ['commerce.orders.id'], name=op.f('fk_payments_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    schema='commerce',
    comment='Payment transactions for orders.'
    )
    op.create_index('ix_payments_order_id', 'payments', ['order_id'], unique=False, schema='commerce')
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='Reviewed product.'),
    sa.Column('customer_id', sa.Integer(), nullable=False, comment='Review author.'),
    sa.Column('rating', sa.SmallInteger(), nullable=False, comment='Star rating from 1 to 5.'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Review headline.'),
    sa.Column('body', sa.Text(), nullable=False, comment='Review text.'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When the review was posted.'),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['customer_id'], ['commerce.customers.id'], name=op.f('fk_reviews_customer_id_customers')),
    sa.ForeignKeyConstraint(['product_id'], ['commerce.products.id'], name=op.f('fk_reviews_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    schema='commerce',
    comment='Product reviews written by customers.'
    )
    op.create_index('ix_reviews_product_id', 'reviews', ['product_id'], unique=False, schema='commerce')
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=300), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', Vector(get_settings().embedding_dimension), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', coalesce(section, '') || ' ' || content)", persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks'))
    )
    op.create_index('ix_document_chunks_document_index', 'document_chunks', ['document_id', 'chunk_index'], unique=True)
    op.create_index('ix_document_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_document_chunks_search_vector', 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False, comment='Returned line item.'),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='Order of the item.'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='Returned product.'),
    sa.Column('customer_id', sa.Integer(), nullable=False, comment='Customer who returned it.'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Units returned.'),
    sa.Column('reason', sa.String(length=40), nullable=False, comment="'defective', 'damaged_in_transit', 'wrong_item', 'not_as_described', 'size_issue' or 'changed_mind'."),
    sa.Column('status', sa.String(length=20), nullable=False, comment="'requested', 'approved', 'rejected' or 'refunded'."),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Amount refunded in BDT (0 unless refunded).'),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False, comment='When the return was requested.'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='When the return was approved/rejected/refunded.'),
    sa.ForeignKeyConstraint(['customer_id'], ['commerce.customers.id'], name=op.f('fk_returns_customer_id_customers')),
    sa.ForeignKeyConstraint(['order_id'], ['commerce.orders.id'], name=op.f('fk_returns_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['commerce.order_items.id'], name=op.f('fk_returns_order_item_id_order_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['commerce.products.id'], name=op.f('fk_returns_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_returns')),
    schema='commerce',
    comment="Product return requests. A refund happened when status = 'refunded'; refund_amount is the money given back."
    )
    op.create_index('ix_returns_product_id', 'returns', ['product_id'], unique=False, schema='commerce')
    op.create_index('ix_returns_requested_at', 'returns', ['requested_at'], unique=False, schema='commerce')
    # ### end Alembic commands ###
    _create_readonly_role()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_returns_requested_at', table_name='returns', schema='commerce')
    op.drop_index('ix_returns_product_id', table_name='returns', schema='commerce')
    op.drop_table('returns', schema='commerce')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_document_chunks_search_vector', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('ix_document_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_document_chunks_document_index', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('ix_reviews_product_id', table_name='reviews', schema='commerce')
    op.drop_table('reviews', schema='commerce')
    op.drop_index('ix_payments_order_id', table_name='payments', schema='commerce')
    op.drop_table('payments', schema='commerce')
    op.drop_index('ix_order_items_product_id', table_name='order_items', schema='commerce')
    op.drop_index('ix_order_items_order_id', table_name='order_items', schema='commerce')
    op.drop_table('order_items', schema='commerce')
    op.drop_table('inventory', schema='commerce')
    op.drop_index('ix_agent_runs_user_created', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_conversation_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_checksum'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_products_category_id', table_name='products', schema='commerce')
    op.drop_table('products', schema='commerce')
    op.drop_index('ix_orders_status', table_name='orders', schema='commerce')
    op.drop_index('ix_orders_order_date', table_name='orders', schema='commerce')
    op.drop_index('ix_orders_customer_id', table_name='orders', schema='commerce')
    op.drop_table('orders', schema='commerce')
    op.drop_table('users')
    op.drop_index('ix_customers_membership_tier', table_name='customers', schema='commerce')
    op.drop_index('ix_customers_country', table_name='customers', schema='commerce')
    op.drop_table('customers', schema='commerce')
    op.drop_table('categories', schema='commerce')
    # ### end Alembic commands ###
    role = _quote_ident(get_settings().sql_readonly_user)
    op.execute(f"REVOKE ALL ON SCHEMA commerce FROM {role}")
    op.execute(f"ALTER DEFAULT PRIVILEGES IN SCHEMA commerce REVOKE SELECT ON TABLES FROM {role}")
    op.execute("DROP SCHEMA IF EXISTS commerce")
